name: Main Branch

on:
  push:
    branches: [ main ]

env:
  GRETEL_PROJECT: judebantony-868a3
  GRETEL_TEST_FILE: gretel_2549b151fd284721b75d4a726e1d1618_dataset.csv
  GRETEL_TEST_OUT_FILE: gretel.csv
  GRETEL_MODEL: 6214794460dc0eccb24afc19
  
jobs:

  syntheticDataDownload:
    name: Download Synthetic Test Data File from Gretel  
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Synthetic Test Data File
      id: myRequest
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.gretel.cloud/projects/${{env.GRETEL_PROJECT}}/models/${{env.GRETEL_MODEL}}/artifact?type=data_preview'
        method: 'GET'
        customHeaders: '{"Authorization": "${{ secrets.GRETEL_TOKEN }}"}'
    - name: Store the Response
      run: cat <<< ${{ toJSON(steps.myRequest.outputs.response) }} > gretel_out.json
    - name: Read the Respose
      id: format_script
      uses: notiz-dev/github-action-json-property@release
      with: 
          path: 'gretel_out.json'
          prop_path: 'data.url'
    - run: curl -X GET "${{steps.format_script.outputs.prop}}" > data_preview.gz
    - run: ls -lst
    - run: gzip -d data_preview.gz
    - run: cat data_preview
    
